### ISSUE TITLE
SSL errors on python 3.5.0

### ISSUE THREAD

**Issue by pathcl** [zach-taylor/splunk_handler#8]
lsanmartin@lsanmartin:~/src/python/splunk$ python test.py 
Traceback (most recent call last):
  File "/home/lsanmartin/.pyenv/versions/3.5.0/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/lsanmartin/.pyenv/versions/3.5.0/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/home/lsanmartin/.pyenv/versions/3.5.0/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/home/lsanmartin/.pyenv/versions/3.5.0/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/home/lsanmartin/.pyenv/versions/3.5.0/lib/python3.5/site-packages/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/lsanmartin/.pyenv/versions/3.5.0/lib/python3.5/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/home/lsanmartin/.pyenv/versions/3.5.0/lib/python3.5/ssl.py", line 747, in __init__
    self.do_handshake()
  File "/home/lsanmartin/.pyenv/versions/3.5.0/lib/python3.5/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/home/lsanmartin/.pyenv/versions/3.5.0/lib/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lsanmartin/.pyenv/versions/3.5.0/lib/python3.5/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/lsanmartin/.pyenv/versions/3.5.0/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lsanmartin/.pyenv/versions/3.5.0/lib/python3.5/site-packages/splunk_handler/**init**.py", line 74, in _async_emit
    verify=self.verify
  File "/home/lsanmartin/.pyenv/versions/3.5.0/lib/python3.5/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, *_kwargs)
  File "/home/lsanmartin/.pyenv/versions/3.5.0/lib/python3.5/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/lsanmartin/.pyenv/versions/3.5.0/lib/python3.5/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/lsanmartin/.pyenv/versions/3.5.0/lib/python3.5/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, *_kwargs)
  File "/home/lsanmartin/.pyenv/versions/3.5.0/lib/python3.5/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)

Exception in Splunk logging handler: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)

lsanmartin@lsanmartin:~/src/python/splunk$ cat test.py 
import logging
from splunk_handler import SplunkHandler

splunk = SplunkHandler(host='host.domain.tld', port='8089', username='user', password='password', index='main')

logging.getLogger('').addHandler(splunk)
logging.warning('hello!')

**Comment by pathcl** [comment]
Well well, this can be fixed just changing verify=True to verify=False :)

**Comment by pathcl** [comment]
https://github.com/zach-taylor/splunk_handler/pull/9

**Comment by sharon-kent** [comment]
Is there a solution for this that doesn't involve setting verify=False? My security team isn't satisfied with that solution, and my Splunk team states the port is presenting the correct certificate. I'm using splunk-handler 3.0.0 and python 3.8.12 but still seeing the same errors.
